---
title: "The issue of ice"
author: "Robert Schlegel"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
description: This vignette explores different approaches to dealing with the detection
  of MCSs in near-ice pixels.
vignette: |
  %\VignetteIndexEntry{Vignette Title} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
bibliography: bibliography.bib
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(fig.width = 6, fig.align = 'center',
                      warning = FALSE, message = FALSE, 
                      tidy = FALSE)
```


## Introduction

While putting together the global analysis of historic marine cold-spells (MCSs) we began to realise that simply inverting the marine heatwave (MHW) algorithm did technically work, but created a couple of unexpected issues that needed to be addressed. These issues stem from the fact that on our planet seawater freezes at roughly -1.8째C. The first, and much more wide-spread issue, was that for most of the near-ice pixels on the planet, the average intra-annual (within one year) variance in sea-surface temperature (SST) could be as little as 0.2째C. The MHW algorithm works on quantiles, and these maths tend not to be very effective with such a small range in values. Indeed, what does it really matter if a MHW/MCS is detected because of a change of 0.05째C from the seasonally expected average? Can that possibly have any effect on local bio/ecology? One obvious solution to this issue, is to not apply the MHW/MCS algorithm to near-ice pixels, but ignoring the issue is not a satisfactory response to it. The other much less common issue is that in some regions of the ocean that do experience a reasonable range in intra-annual SST, it can be possible that the category system will not be able to detect the higher category of events because the the thresholds for these events may be colder than -1.8째C. I know that sentence probably didn't make any sense, which is why we will be providing extensive examples below that illustrate these two issues and outline the steps that one may take to address them. All of the code necessary to do so is documented and we welcome anyone interested in this issue to contact us and to use the code themselves in any projects.

Before we get into the weeds on all of these technical issue I must reiterate what is stated in the paper that this vignette was written to accompany. That the authors all agreed that ultimately, for a global analysis, it was better to use the "original" definition from @Hobday2016 with a 10th percentile threshold (rather than 90th percentile) because this would provide globally consistent and comparable results. It was also decided to stick to the category convention laid out in @Hobday2018. The options that are laid out below are done so with the intention that they may be more useful to researchers investigating MCSs at a more regional scale. Or perhaps for researchers that need to work in near-ice areas and are not satisfied with how the MCS algorithm responds to those areas.

In the following sections we will first look at considerations for how to deal with the less common issue of when it becomes impossible to detect more intense categories of MCSs in a time series. Building off of the theory demonstrated in that section we will then look at what to do about MCS detection in near-ice areas that experience very little intra-annual variance in SST. We will wrap up this vignette by looking at how much these tweaks to the algorithm can have a global effect, and how sensitive global results are to these tweaks.


## Impossible categories


## Chilly all year long


## Thinking globally, acting locally


## References

